# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webpage_offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nazwisko')),
                ('phone', models.IntegerField(verbose_name='Telefon')),
                ('date_of_birth', models.CharField(blank=True, max_length=12, null=True, verbose_name='Data urodzenia')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data ropoczęcia')),
                ('end_date', models.DateField(verbose_name='Data zakończenia')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='webpage_offer.Offer', verbose_name='Oferta')),
            ],
        ),
        migrations.CreateModel(
            name='TourParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'reserved'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='reserved', max_length=20, verbose_name='Status')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='webpage_tour.Participant', verbose_name='Uczestnik')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='webpage_tour.Tour', verbose_name='Wycieczka')),
            ],
        ),
    ]
