# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage_tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='webpage_tour.Participant'),
        ),
        migrations.AlterField(
            model_name='tourparticipant',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='webpage_tour.Tour'),
        ),
    ]
