# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage_offer', '0014_auto_20190325_1831'),
        ('webpage_tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'reserved'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='reserved', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data ropoczęcia')),
                ('end_date', models.DateField(verbose_name='Data zakończenia')),
                ('holiday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidays', to='webpage_offer.Holiday', verbose_name='Wakacje')),
            ],
        ),
        migrations.AddField(
            model_name='holidayparticipant',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='webpage_tour.HolidayTour', verbose_name='Wakacje'),
        ),
        migrations.AddField(
            model_name='holidayparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='webpage_tour.Participant', verbose_name='Uczestnik'),
        ),
    ]
