# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage_tour', '0002_auto_20181018_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
