# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-29 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage_tour', '0002_auto_20190328_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayparticipant',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='holidayparticipant',
            name='participant',
        ),
        migrations.DeleteModel(
            name='HolidayParticipant',
        ),
    ]
