# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage_tour', '0003_participant_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
