# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage_tour', '0004_auto_20181102_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='webpage_offer.Offer'),
        ),
    ]
