# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('school_trip', 'oferta dla szkół'), ('work_trip', 'oferta dla firm'), ('pilgrimage', 'pielgrzymka')], max_length=20)),
                ('direction', models.CharField(max_length=255)),
                ('duration_in_days', models.IntegerField()),
                ('short_descr', models.TextField(max_length=200)),
                ('schedule', tinymce.models.HTMLField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('selected_sort', models.IntegerField(blank=True, null=True)),
                ('recommended', models.BooleanField(default=False)),
                ('recommended_sort', models.IntegerField(blank=True, null=True)),
                ('withdrawn', models.BooleanField(default=False)),
            ],
        ),
    ]
