# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage_offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_descr', models.TextField(max_length=200)),
                ('schedule', tinymce.models.HTMLField()),
            ],
        ),
    ]
