# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage_offer', '0002_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_descr', models.TextField(max_length=200)),
                ('entry', models.TextField()),
                ('entry_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
